# Basic
title: YunsChou
subtitle: 既然选择了远方，便只顾风雨兼程
description: 我是YunChou，一名iOS开发者，这里是我用来记录平时学习的地方
welcome_message: 欢迎你的访问
creator: <a href="http://yunschou.github.io">@YunsChou</a>

url: "http://yunschou.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://yunschou.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: YunsChou
    github: YunsChou
    mail: YunsChou@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
